# Generated by Django 5.1.3 on 2024-12-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'футбол'), ('tennis', 'теннис'), ('bowling', 'боулинг'), ('beach volleyball', 'пляжный волейбол'), ('volleyball', 'волейбол'), ('ice hockey', 'хоккей на льду'), ('chess', 'шахматы')], max_length=20)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('location', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='joined_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='games_game_created_1f2afd_idx')],
            },
        ),
    ]
